### ISSUE TITLE
'iterator' module

### ISSUE THREAD

**Issue by WGBmushi** [YangSVM/commonroad_planner#1]
Hi, what's the 'iterator' module? Is this a custom module, or is it installable?
`from iterator import scenario_iterator_interactive, scenario_iterator_non_interactive, _search_interactive_scenarios`

Also, the 'simulation' module. 
`from simulation.simulations import load_sumo_configuration`
Even though I have installed 'simulation'  with pip still prompts invalid as 'ModuleNotFoundError: No module named 'simulation.utility''. I am confused about this.

**Comment by YangSVM** [comment]
please check the official  gitlab repo(https://gitlab.lrz.de/tum-cps).
